version: '3.9'

services:
  db:
    container_name: budget-manager
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: budget-manager
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: budget-manager
    ports:
      - '5432:5432'